#!/usr/bin/env python
"""
This is a small script that does the equivalent of multicrab.
"""
import os
from optparse import OptionParser

from CRABAPI.RawCommand import crabCommand
from CRABClient.ClientExceptions import ClientException
from httplib import HTTPException


def getOptions():
    """
    Parse and return the arguments provided by the user.
    """
    usage = ("Usage: %prog --crabCmd CMD [--workArea WAD --crabCmdOpts OPTS]"
             "\nThe multicrab command executes 'crab CMD OPTS' for each project directory contained in WAD"
             "\nUse multicrab -h for help")

    parser = OptionParser(usage=usage)

    parser.add_option('-c', '--crabCmd',
                      dest = 'crabCmd',
                      default = '',
                      help = "crab command",
                      metavar = 'CMD')

    parser.add_option('-w', '--workArea',
                      dest = 'workArea',
                      default = '',
                      help = "work area directory (only if CMD != 'submit')",
                      metavar = 'WAD')

    parser.add_option('-o', '--crabCmdOpts',
                      dest = 'crabCmdOpts',
                      default = '',
                      help = "options for crab command CMD",
                      metavar = 'OPTS')

    parser.add_option('-v', '--crabJobsVersion',
                      dest = 'crabJobsVersion',
                      default = '', 
                      help = "options for crab jobs version",
                      metavar = 'VERSION')


    (options, arguments) = parser.parse_args()

    if arguments:
        parser.error("Found positional argument(s): %s." % (arguments))
    if not options.crabCmd:
        parser.error("(-c CMD, --crabCmd=CMD) option not provided.")
    if options.crabCmd != 'submit':
        if not options.workArea:
            parser.error("(-w WAR, --workArea=WAR) option not provided.")
        if not os.path.isdir(options.workArea):
            parser.error("'%s' is not a valid directory." % (options.workArea))

    return options


def main():

    options = getOptions()

    # The submit command needs special treatment.
    if options.crabCmd == 'submit':

        #--------------------------------------------------------
        # This is the base config:
        #--------------------------------------------------------
        from CRABClient.UserUtilities import config #, getUsernameFromSiteDB
        config = config()

        config.General.requestName = None
        config.General.workArea = 'crabOutput2018GEN_nofilter_DPSJJ_%s' % (options.crabJobsVersion)
        config.General.transferOutputs = True
        config.General.transferLogs = True

        config.JobType.pluginName = 'Analysis'
        config.JobType.psetName = 'GenAnalyzer_cfg.py'
        #config.JobType.outputFiles = ['GEN_MC.root']

        config.Data.inputDataset = None
        config.Data.inputDBS = 'phys03'
        config.Data.splitting = 'FileBased' #'LumiBased'
        config.Data.unitsPerJob = 3
        #config.Data.totalUnits = 30

        #config.Data.outLFNDirBase = '/store/user/%s/' % (getUsernameFromSiteDB())
        #config.Data.outLFNDirBase = '/store/group/lpcmuon/Run2017/'
        #config.Data.outLFNDirBase = '/store/group/lpcmuon/fourmuonMC'
        #config.Data.outLFNDirBase = '/store/user/%s/FourMuon_Analysis/Charmonium_Skim_MC/2017'% (getUsernameFromSiteDB())
        config.Data.outLFNDirBase = '/store/user/cdozen/FourMuon_Analysis/DPS_MC_Ntuples/No_GenFilter/'
        config.Data.publication = True
        config.Data.outputDatasetTag = None
        config.Site.storageSite = 'T3_US_FNALLPC' # Choose your site. 
        #--------------------------------------------------------

        # Will submit one task for each of these input datasets.
        inputDatasets = [
                        '/DPSToJJ_13TeV_pythia8/zhenhu-crab_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-GENSIM-DPSTo4mu-noGenCut-v2-391455752ee5283724f21c0b29d91758/USER'
                        
                        #'/SPSToJJ_13TeV_pythia8/zhenhu-crab_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-GENSIM-SPSTo4mu-noGenCut-v1-7beb0e22b11525f1abd96d186df735fb/USER',
                        #'/DPSToJJ_13TeV_pythia8/zhenhu-crab_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-GENSIM-DPSTo4mu-noGenCut-v2-391455752ee5283724f21c0b29d91758/USER'
                        
                        #    '/SPSToYY_13TeV_pythia8/zhenhu-crab_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-GENSIM-SPSTo4mu-noGenCut-v1-331942ca7c62d6248afda3f7eafd5722/USER',
                         #   '/DPSToYY_13TeV_pythia8/zhenhu-crab_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-GENSIM-DPSTo4mu-noGenCut-v2-dc5fbfe9916eed64ac61ef5d7348f2d4/USER'
                        ]

        for inDS in inputDatasets:
            # inDS is of the form /A/B/C. Since B is unique for each inDS, use this in the CRAB request name.
            PD = inDS.split('/')[1]
            Run = inDS.split('/')[2].split('-')[1]
            config.General.requestName = 'Rootfile-%s-%s-%s' % (PD, options.crabJobsVersion, Run)
            #config.General.requestName = 'BPHSkim-%s-%s' % (PD, options.crabJobsVersion)
            config.Data.inputDataset = inDS
            config.Data.outputDatasetTag = 'GenRoot-%s-%s' % (options.crabJobsVersion, Run)
            #config.Data.outputDatasetTag = 'BPHSkim-%s' % (options.crabJobsVersion)
				# Submit.
            try:
                print "Submitting for input dataset %s" % (inDS)
                crabCommand(options.crabCmd, config = config, *options.crabCmdOpts.split())
            except HTTPException as hte:
                print "Submission for input dataset %s failed: %s" % (inDS, hte.headers)
            except ClientException as cle:
                print "Submission for input dataset %s failed: %s" % (inDS, cle)

    # All other commands can be simply executed.
    elif options.workArea:

        for dir in os.listdir(options.workArea):
            projDir = os.path.join(options.workArea, dir)
            if not os.path.isdir(projDir):
                continue
            # Execute the crab command.
            msg = "Executing (the equivalent of): crab %s --dir %s %s" % (options.crabCmd, projDir, options.crabCmdOpts)
            print "-"*len(msg)
            print msg
            print "-"*len(msg)
            try:
                crabCommand(options.crabCmd, dir = projDir, *options.crabCmdOpts.split())
            except HTTPException as hte:
                print "Failed executing command %s for task %s: %s" % (options.crabCmd, projDir, hte.headers)
            except ClientException as cle:
                print "Failed executing command %s for task %s: %s" % (options.crabCmd, projDir, cle)





 
if __name__ == '__main__':
    main()
